baseURL = "https://itinsight.online/"
languageCode = "en-us"
title = "IT Insight Online"

theme = "jeffprod"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"

